source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'ErrorUtilities_Example' do
  pod 'ErrorUtilities', :path => '../'

  target 'ErrorUtilities_Tests' do
    inherit! :search_paths

  end
end
